name: Deploy FastAPI to GHCR

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

env:
  GHCR: "ghcr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # for publishing to GHCR
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v3

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ${{env.GHCR}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push FastApi Image'
        run: |
          docker buildx build --push -t ${{env.GHCR}}/${{github.actor}}/fast-api:latest .
