name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v3

      - name: 'Login to GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push FastApi Image'
        run: |
          docker build . -t ghcr.io/tiamat-azure/fast-api:latest
          docker push ghcr.io/tiamat-azure/fast-api:latest